#!/bin/bash

set -e

cd
sudo apt-get update
sudo apt-get upgrade -y
oldhostname="$(hostname)"
# Take the new hostname as an input param!
newhostname="$(whoami)-wsl"

# !!! Delete existing/autogenerated config !!!
sudo truncate -s 0 /etc/wsl.conf
sudo truncate -s 0 /etc/resolv.conf

echo -e "[boot]" | sudo tee -a /etc/wsl.conf
echo -e "systemd=true" | sudo tee -a /etc/wsl.conf # Enable systemd (for neovim-snap)

echo -e "[network]" | sudo tee -a /etc/wsl.conf
echo -e "hostname=${newhostname}" | sudo tee -a /etc/wsl.conf # Set hostname
echo -e "generateHosts=false" | sudo tee -a /etc/wsl.conf # Disable WSL /etc/hosts override
echo -e "generateResolvConf=false" | sudo tee -a /etc/wsl.conf # Disable WSL /etc/resolv.conf override

# DNS setup
sudo resolvectl dns eth0 1.1.1.1 4.4.4.4
echo -e "nameserver 1.1.1.1" | sudo tee -a /etc/resolv.conf # DNS 1
echo -e "nameserver 4.4.4.4" | sudo tee -a /etc/resolv.conf # DNS 2

sudo sed -i "s/$oldhostname/$newhostname/g" /etc/hosts

sudo locale-gen --purge en_US.UTF-8
echo -e 'LANG="en_US.UTF-8"\nLANGUAGE="en_US:en"\n' | sudo tee /etc/default/locale

# exit
