#!/bin/bash

set -e

cd
sudo apt-get update
sudo apt-get upgrade -y
oldhostname="$(hostname)"
newhostname="$(cmd.exe /C hostname | tr -d '\n' | tr -d '\r')-wsl" # Generate "HOSTSYSTEM-wsl" hostname

# !!! Delete existing/autogenerated config !!!
sudo truncate -s 0 /etc/wsl.conf
sudo truncate -s 0 /etc/resolv.conf

echo -e "[boot]" | sudo tee -a /etc/wsl.conf
echo -e "systemd=true" | sudo tee -a /etc/wsl.conf # Enable systemd

echo -e "[network]" | sudo tee -a /etc/wsl.conf
echo -e "hostname=${newhostname}" | sudo tee -a /etc/wsl.conf # Set hostname
echo -e "generateHosts=false" | sudo tee -a /etc/wsl.conf # Disable WSL /etc/hosts override
echo -e "generateResolvConf=false" | sudo tee -a /etc/wsl.conf # Disable WSL /etc/resolv.conf override

# DNS setup
echo -e "[Resolve]" | sudo tee -a /etc/systemd/resolved.conf
echo -e "DNS=1.1.1.1 4.4.4.4" | sudo tee -a /etc/systemd/resolved.conf
echo -e "Domains=domain.com" | sudo tee -a /etc/systemd/resolved.conf

echo -e "nameserver 1.1.1.1" | sudo tee -a /etc/resolv.conf # DNS 1
echo -e "nameserver 4.4.4.4" | sudo tee -a /etc/resolv.conf # DNS 2

sudo sed -i "s/$oldhostname/$newhostname/g" /etc/hosts # Set new hostname for local name resolution
sudo sed -i 's/session    optional   pam_motd.so/#session    optional   pam_motd.so/' /etc/pam.d/login # Disable Ubuntu Message of the day

sudo locale-gen --purge en_US.UTF-8
echo -e 'LANG=en_US.UTF-8\nLANGUAGE=en_US:en\n' | sudo tee /etc/default/locale

touch ~/.hushlogin # Disable ubuntu motd, since this would be overwritten anyway

# exit

