#!/bin/bash

set -e

cd
sudo apt-get update
sudo apt-get upgrade -y
oldhostname="$(hostname)"
newhostname="$(cmd.exe /C hostname | tr -d '\n' | tr -d '\r')-wsl" # Generate "HOSTSYSTEM-wsl" hostname

# Overrides existing/autogenerated config!
sudo tee /etc/wsl.conf > /dev/null <<EOF
[network]
hostname=${newhostname} # Set hostname
generateHosts=false # Disable WSL /etc/hosts override
generateResolvConf=false # Disable WSL /etc/resolv.conf override

[interop]
enabled=true # Allow WSL to run .exe files
appendWindowsPath=true
EOF

# DNS setup
sudo tee /etc/resolv.conf > /dev/null <<EOF
nameserver 1.1.1.1 # DNS 1
nameserver 4.4.4.4 # DNS 2
EOF

sudo sed -i "s/$oldhostname/$newhostname/g" /etc/hosts # Set new hostname for local name resolution
sudo sed -i 's/session    optional   pam_motd.so/#session    optional   pam_motd.so/' /etc/pam.d/login # Disable Ubuntu Message of the day

sudo locale-gen --purge en_US.UTF-8
echo -e 'LANG=en_US.UTF-8\nLANGUAGE=en_US:en\n' | sudo tee /etc/default/locale

touch ~/.hushlogin # Disable ubuntu motd, since this would be overwritten anyway

# Install dotfiles repo
mkdir -p ~/git
git clone https://github.com/hasenhuettl/dotfiles.git ~/git/dotfiles
bash ~/git/dotfiles/bootstrap.sh

# exit

